// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations precisam de session mode (CREATE TABLE, etc) — usa DIRECT_URL
    // (Session Pooler 5432 no Supabase) que mantém sessão persistente.
    // Runtime (queries normais) usa DATABASE_URL via adapter-pg em src/lib/db.ts.
    // Fallback pra DATABASE_URL se DIRECT_URL não estiver setada (compat dev local).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
